services:
  test-microservice:
    build:
      context: ../test-microservice
    env_file:
      - ./envs/test-microservice.env
    volumes:
      - ../test-microservice/src:/app/src
    environment:
      - DEBUG=${DEBUG}
      - SERVICE_PORT=${SERVICE_PORT:-8000}
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port ${SERVICE_PORT:-8000} 
    networks:
      - iot_hub_net

  telemetry-validator:
    build:
      context: ../Telemetry-Validator-Service
    env_file:
      - ./envs/telemetry-validator.env
    volumes:
      - ../Telemetry-Validator-Service/app:/app
    environment:
      - VALIDATOR_DEBUG=true
    networks:
      - iot_hub_net
