services:

  telemetry-validator:
    build:
      context: ../Telemetry-Validator-Service
    env_file:
      - ./envs/telemetry-validator.env
    volumes:
      - ../Telemetry-Validator-Service/app:/app
    environment:
      - VALIDATOR_DEBUG=true
    networks:
      - iot_hub_net

  redis-service:
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=local_dev_password
