x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - iot_hub_net
    logging: *default-logging
    ports:
      - "5432:5432"

  test-microservice:
    image: ghcr.io/iot-hub-alpha/test-microservice:0.1
    ports:
      - "8000:8000"
    env_file:
      - envs/test-microservice.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - iot_hub_net
    logging: *default-logging

networks:
  iot_hub_net:
    driver: bridge

volumes:
  postgres_data:
